### ISSUE TITLE
The new version seems to be there, Tencent server, you can't enter the game

### ISSUE THREAD

**Issue by makabaka2869** [rumi-chan/Sakura#18]
The new version seems to be there, Tencent server, you can't enter the game

**Comment by rumi-chan** [comment]
> The new version seems to be there, Tencent server, you can't enter the game

Game crash or sth?

**Comment by makabaka2869** [comment]
> > 新版本好像有，腾讯服务器，你进不了游戏
> 
> 游戏崩溃还是崩溃？

I am on the Tencent server, I can't enter the page of loading games. I tried to be in the RIOT server in Taiwan. Entering the pairing game will always show Sakura errors, and there is no interface in the game.

**Comment by rumi-chan** [comment]
> nd there is no interface in the game.
Like this?
![image](https://github.com/rumi-chan/Sakura/assets/59478113/6adedfa4-7e76-476b-917d-09ab93fd31f8)

**Comment by makabaka2869** [comment]
> > 游戏中没有界面。 喜欢这个？
> > ![图像](https://private-user-images.githubusercontent.com/59478113/289233799-6adedfa4-7e76-476b-917d-09ab93fd31f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwOTc1MzcsIm5iZiI6MTcwMjA5NzIzNywicGF0aCI6Ii81OTQ3ODExMy8yODkyMzM3OTktNmFkZWRmYTQtN2U3Ni00NzZiLTkxN2QtMDlhYjkzZmQzMWY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA5VDA0NDcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1MzU1YWQxY2RmMTU3OGRjYThiNWJhNWE0N2FmOGY3OGVlOGE4OGJhN2I1OTkzM2FiZjM0YWYyNTcyZGQwZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7mVx7DLTmqWmtVGsRiXvXnQGkd_KCsWNXssSoQir5yk)

Yes, Taiwan RIOT will show this error

**Comment by makabaka2869** [comment]
> > 游戏中没有界面。 喜欢这个？
> > ![图像](https://private-user-images.githubusercontent.com/59478113/289233799-6adedfa4-7e76-476b-917d-09ab93fd31f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwOTc1MzcsIm5iZiI6MTcwMjA5NzIzNywicGF0aCI6Ii81OTQ3ODExMy8yODkyMzM3OTktNmFkZWRmYTQtN2U3Ni00NzZiLTkxN2QtMDlhYjkzZmQzMWY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA5VDA0NDcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1MzU1YWQxY2RmMTU3OGRjYThiNWJhNWE0N2FmOGY3OGVlOGE4OGJhN2I1OTkzM2FiZjM0YWYyNTcyZGQwZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7mVx7DLTmqWmtVGsRiXvXnQGkd_KCsWNXssSoQir5yk)

Using the old version of the sakura in Tencent's server, it can be used normally, and there will be errors in the new version. In the Taiwan RiOT server, the old and new versions seem to be unable to use it normally

**Comment by makabaka2869** [comment]
> > 游戏中没有界面。
> 
> 喜欢这个？
> 
> ![图像](https://private-user-images.githubusercontent.com/59478113/289233799-6adedfa4-7e76-476b-917d-09ab93fd31f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwOTc3OTYsIm5iZiI6MTcwMjA5NzQ5NiwicGF0aCI6Ii81OTQ3ODExMy8yODkyMzM3OTktNmFkZWRmYTQtN2U3Ni00NzZiLTkxN2QtMDlhYjkzZmQzMWY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA5VDA0NTEzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhNmI0MjllY2E1MWZhOTNiZDc5MTM2Mjg2MTVmMmM4ZDUzNzdmNjEyNmQ2NjJkZjVmNGNjNDI1NzA1MTRmNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SNNorqN8we68vGBODrNDUDv3jm6y3WQdx8htLTuF5dY)

Using the new version of Sakura, in the Tencent server, there will not be any errors, but you can't enter the loading page. I modify the file name to the HID.DLL method into the GAME folder of the League of Legends. I'm not sure Is it because my operation is caused by my operation

**Comment by rumi-chan** [comment]
I just created a TW account and it works fine
![image](https://github.com/rumi-chan/Sakura/assets/59478113/3950546b-6267-4a73-98ed-3b0498666b00)

**Comment by makabaka2869** [comment]
> I just created a TW account and it works fine ![image](https://private-user-images.githubusercontent.com/59478113/289235446-3950546b-6267-4a73-98ed-3b0498666b00.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxMDM4NDQsIm5iZiI6MTcwMjEwMzU0NCwicGF0aCI6Ii81OTQ3ODExMy8yODkyMzU0NDYtMzk1MDU0NmItNjI2Ny00YTczLTk4ZWQtM2IwNDk4NjY2YjAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA5VDA2MzIyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjNWEyMDc4YWI2MTM3MmI3ODc4M2UwZjkxMjIzZTQ1NjA2ZGQ0YmI1Nzg2OGUwMjZiNDQwN2E5M2Y4YjdkOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2VxYQO7NVxhabVOH70uinFQ82VJz2LRiQ77IEnPGqwc)

I modify the file name to the HID.DLL method into the GAME folder of the League of Legends. I'm not sure Is it because my operation is caused by my operation

**Comment by BakaFT** [comment]
This guy's words is misleading due to translation issue.

Old version Sakura is working fine on Tencent 13.24 is just because old `GameClient` pattern is still working.

I gave a test using latest Sakura on Tencent 13.24 and find out the game process died very early **without any MessageBox alert**, I can not even see the loading screen. And I can confirm that pattern codes in latest Sakura is also **working fine on Tencent**.

So I guess there should be something wrong other than pattern code.

**Comment by BakaFT** [comment]
I have found the reason why it breaks and fixed it.
This bug only happens in CN installs, and I've pushed a fix to @rumi-chan , just wait for next update.

![image](https://github.com/rumi-chan/Sakura/assets/8694498/db76b635-c939-4032-b265-2603be06cf39)

**Comment by makabaka2869** [comment]
> 我已经找到了它损坏的原因并修复了它。此错误仅发生在 CN 安装中，我已经推送了修复程序，只需等待下一次更新。
> 
> ![图像](https://private-user-images.githubusercontent.com/8694498/289711282-db76b635-c939-4032-b265-2603be06cf39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNDU1OTQsIm5iZiI6MTcwMjM0NTI5NCwicGF0aCI6Ii84Njk0NDk4LzI4OTcxMTI4Mi1kYjc2YjYzNS1jOTM5LTQwMzItYjI2NS0yNjAzYmUwNmNmMzkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTJUMDE0MTM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjkyZGE0YmI3OTc1YTEzZGUzZDYwZWE1ZDU1YWQ4Zjc0ZDY3NmVhOGYzMDM3MDE0Nzg3NWIxMzc4YTMzMTY2YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.AVx5YtVqCSZMFXqizDyQEQw2HHg3X21qHXonHri3Coc)

Thank you very much

**Comment by makabaka2869** [comment]
> > 新版本好像有，腾讯服务器，你进不了游戏
> 
> 游戏崩溃还是崩溃？

Thank you very much，Thank you very much

**Comment by makabaka2869** [comment]
> > nd there is no interface in the game.
> 
> Like this?
> 
> ![image](https://private-user-images.githubusercontent.com/59478113/289233799-6adedfa4-7e76-476b-917d-09ab93fd31f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNDY1NTAsIm5iZiI6MTcwMjM0NjI1MCwicGF0aCI6Ii81OTQ3ODExMy8yODkyMzM3OTktNmFkZWRmYTQtN2U3Ni00NzZiLTkxN2QtMDlhYjkzZmQzMWY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDAxNTczMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhNWNhNmEzZjY5YjVjM2UwMjg5ZTBiODMzMWRiOTk4ZDZhNWM3OWIzN2QwYzZkMjU1NmMyNzA2ZTc2OGQ2ZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cN9jBgekkPtEBikaIhW6A1pAkoJPz0SNZGkRjoXWobU)

Even in the Taiwan server, I tried to modify the Sakura file to HID.DLL and put it in the game folder. It still showed this pop-up error. If I chose to click to confirm, the game would crash.

**Comment by makabaka2869** [comment]
> > > 游戏中没有界面。
> > 
> > 
> > 喜欢这个？
> > ![图像](https://private-user-images.githubusercontent.com/59478113/289233799-6adedfa4-7e76-476b-917d-09ab93fd31f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNDY1NTAsIm5iZiI6MTcwMjM0NjI1MCwicGF0aCI6Ii81OTQ3ODExMy8yODkyMzM3OTktNmFkZWRmYTQtN2U3Ni00NzZiLTkxN2QtMDlhYjkzZmQzMWY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDAxNTczMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhNWNhNmEzZjY5YjVjM2UwMjg5ZTBiODMzMWRiOTk4ZDZhNWM3OWIzN2QwYzZkMjU1NmMyNzA2ZTc2OGQ2ZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cN9jBgekkPtEBikaIhW6A1pAkoJPz0SNZGkRjoXWobU)
> 
> 即使在台湾服务器中，我也尝试将樱花文件修改为 HID.DLL 并将其放入游戏文件夹中。它仍然显示此弹出错误。如果我选择单击确认，游戏将崩溃。

Even if an error pops up, there is still no Sakura interface in the game

**Comment by makabaka2869** [comment]
> 我已经找到了它损坏的原因并修复了它。此错误仅发生在 CN 安装中，我已经推送了修复程序，只需等待下一次更新。
> 
> ![image](https://private-user-images.githubusercontent.com/8694498/289711282-db76b635-c939-4032-b265-2603be06cf39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NDQyODYsIm5iZiI6MTcwMzc0Mzk4NiwicGF0aCI6Ii84Njk0NDk4LzI4OTcxMTI4Mi1kYjc2YjYzNS1jOTM5LTQwMzItYjI2NS0yNjAzYmUwNmNmMzkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjhUMDYxMzA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODEyZTEzNjRmZTYyNzVhZTU4ZmU3YjAwYmI3OGEwYWViNTgwN2JjMWZkZDc2ODE5MDg4ZmFhYzcyY2FmNjE4NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.0zItCdzrACGNWiZS53MUkCvawEdk4WK8TyQHRu_favo)

First of all, thank you for your contribution. I downloaded the latest version and can enter the game. However, the game will crash immediately after entering. This is true for both Tencent servers and Taiwan servers. I don’t know what went wrong. This makes me very sad. It’s distressing, but the old version of Sakura can still be used normally.

**Comment by BakaFT** [comment]
https://github.com/rumi-chan/Sakura/releases/tag/v1.0
Read release changelogs carefully.

> Known bugs
>- Crash game when choose Default option
>- Some skins of little legends lead to game crash (River Sprite, Socialite Nixie,..)
>- Remember to Delete your old config file in Documents/Sakura before using it!!! Otherwise it'll crash.

这不用我翻译了吧？
